# Hugo configuration file
baseURL = "https://dzyla.github.io/scientific_website_template/"
languageCode = "en-us"
title = "Bio Lab"
theme = "scilab"

[params]
  highlightColor = "#cfb87c"         # your brand accent
  ga4MeasurementID = "G-XXXXXXXXXX"  # set your GA4 ID here
  # Use one or more verification tokens below after you register each service.
  verification_google = ""           # e.g., "abc123..."
  verification_bing = ""             # e.g., "BingSiteAuthCode"
  verification_yandex = ""           # optional
  organization_name = "Bio Lab"
  organization_logo = "/favicon.svg"
  organization_url  = "https://dzyla.github.io/scientific_website_template/"
  twitter_handle = "@dawidzyla"     # optional, for cards

canonifyURLs = false

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Respect user privacy while keeping analytics useful
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.youtube]
    privacyEnhanced = true

[menu]
  [[menu.main]]
    name = "Research"
    pageRef = "research"
    weight = 1

  [[menu.main]]
    name = "Team"
    pageRef = "team"
    weight = 2

  [[menu.main]]
    name = "Publications"
    pageRef = "publications"
    weight = 3

  [[menu.main]]
    name = "Resources"
    pageRef = "resources"
    weight = 4

  [[menu.main]]
    name = "Philosophy"
    pageRef = "philosophy"
    weight = 5

  [[menu.main]]
    name = "Contact"
    pageRef = "contact"
    weight = 6
