# Hugo configuration file
title = "Bio Lab"
languageCode = "en-us"
theme = "scilab"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 1
  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3
  [[menu.main]]
    name = "Resources"
    url = "/resources"
    weight = 4
  [[menu.main]]
    name = "Protocols"
    url = "/protocols"
    weight = 5
  [[menu.main]]
    name = "Lab Fun"
    url = "/labfun"
    weight = 6
  [[menu.main]]
    name = "Philosophy"
    url = "/philosophy"
    weight = 7
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 8
